# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-11 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books_app.Authors'),
        ),
    ]
